Made google-services.json as  optional file.
Samagra-Development/odk-collect-extension pull request #48
Opened 2023-05-07 20:38 UTC by 098suraj

Closes #43 

#### What has been done to verify that this works as intended?
       I have built and tested the sample app for the basic functionalities and it seems to be working for all the current features. I 
      have also manually verified that the optional Google services JSON file is handled correctly and does not cause any issues or 
      crashes.
#### Why is this the best possible solution? Were any other approaches considered?
         For making the Google services JSON file optional, we need to check if it exists, and based on that, we apply plugins and 
        dependencies for the same. This is the best possible solution as it provides flexibility for developers to include or exclude 
        the file as needed, without causing any issues with the app.
#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
         This change makes the Google services JSON file optional, which means that developers can choose to include or exclude 
        it as needed. This should not affect the behavior of the app in any significant way. However, there is a risk of regression if 
       the code changes inadvertently affect the handling of the optional file or if there are issues with the dependencies that are 
       included/excluded based on the presence of the file.

2023-05-08 13:54 UTC, chinmoy12c requested changes
Hey @098suraj , thanks for the PR. Currently, if we do not include google-services.json in our project, but still change the annotation in `FormsNetworkInteractorComponent` to `@FirebaseStorage` instead of `@GenericNetworkStorage` the app will crash with `ClassNotFoundException`. We need to gracefully handle this inside the code somehow (and also document the annotation about this issue).

2023-05-08 13:54 UTC, chinmoy12c commented on sample/build.gradle
> +    println("google-services.json not found .Firebase services will not be availabe ")
nit, please correct the position of fullstop.

2023-05-08 13:54 UTC, chinmoy12c commented on sample/build.gradle
> -    implementation (Dependencies.opencsv) {
nit add the deleted space.

2023-05-08 13:54 UTC, chinmoy12c commented on sample/build.gradle
> -apply plugin: 'com.google.firebase.crashlytics'
nit add a newline at the end of file.

2023-05-19 07:45 UTC, chinmoy12c commented
Hey @098suraj, are you planning to complete this?

2023-06-06 15:23 UTC, 098suraj commented
Hey @chinmoy12c, I have made a few changes kindly look into it.
I have used `getIdentifier` to get the  google app id as we can't check if google services json is available at runtime.
So, I check for the  google app id  and if it is present, we can use `FirebaseStorageHandler` or `GenericNetworkStorageHandler` as a default case.

2023-06-07 13:23 UTC, chinmoy12c requested changes

2023-06-07 13:23 UTC, chinmoy12c commented on odk/extension/src/main/java/io/samagra/odk/collect/extension/components/FormsNetworkInteractorComponent.kt
> +    @FirebaseStorage
Please leave this at `@GenericNetworkStorage`.

2023-06-07 13:44 UTC, 098suraj commented on odk/extension/src/main/java/io/samagra/odk/collect/extension/components/FormsNetworkInteractorComponent.kt
> +    @FirebaseStorage
I have done the changes, @chinmoy12c kindly check it.

2023-06-13 10:37 UTC, merged