Feature/fix35
Samagra-Development/odk-collect-extension pull request #51
Opened 2023-05-10 20:47 UTC by shivenducs1136

Closes #35 

#### What has been done to verify that this works as intended?
` The sample app I built and tested for the key functions appears to function with all the features that are currently available. ` 

#### Why is this the best possible solution? Were any other approaches considered?
` The best possible solution is to move the methods, and their implementations to formsInteractor & ODKFormsHandler also we have to use formsInteractor object to use the required methods in the ODKFeatureTesterActivity` 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
` This change would not affect in user perspective `

#### Does this change require updates to documentation?
` Yes, we need to update the readme.md file and move the required methods to appropriate places. `

2023-05-12 07:03 UTC, chinmoy12c requested changes

2023-05-12 07:03 UTC, chinmoy12c commented on odk/extension/src/main/java/io/samagra/odk/collect/extension/modules/FormsInteractorModule.kt
> +        val formsInteractor = DaggerFormsInteractorComponent.factory().create(application).getFormsInteractor()
You're trying to create an instance of `FormsInteractor` inside the module `FormsInteractorModule` (This method is called when an instance of `FormsInteractor` is needed). This leads to the calling of this method in a loop.
This code is essentially trying to call the constructor of class A inside the constructor of class A (hence the progress bar of the sample app never closes because it's stuck in this loop forever).

2023-05-12 07:03 UTC, chinmoy12c commented on odk/extension/src/main/java/io/samagra/odk/collect/extension/handlers/ODKFormsHandler.kt
> +    private var formsInteractor: FormsInteractor,
You're accepting a `FormsInteractor`  inside the constructor of `ODKFormsHandler` which is itself an implementation of `FormsInteractor`.

2023-05-12 07:03 UTC, chinmoy12c commented on odk/extension/src/main/java/io/samagra/odk/collect/extension/handlers/ODKFormsHandler.kt
> +                    formsInteractor.openFormWithFormId(formId, context)
you do not need to use `formsInteractor` here. You're already calling `openFormWithForId` inside an implementation of `FormsInteractor`.

2023-05-19 07:46 UTC, chinmoy12c commented
Hey @shivenducs1136, are you planning to complete this?

2023-05-19 07:55 UTC, shivenducs1136 commented
Yes will be completing it by today.

2023-05-20 12:15 UTC, closed without merging