Moved openForm(),openSavedForm and prefillAndOpenForm() to FormsInteractor
Samagra-Development/odk-collect-extension pull request #54
Opened 2023-05-20 13:06 UTC by shivenducs1136

Closes #35 

#### What has been done to verify that this works as intended?
` The sample app I built and tested for the key functions appears to function with all the features that are currently available. ` 

#### Why is this the best possible solution? Were any other approaches considered?
` The best possible solution is to move the methods, and their implementations to formsInteractor & ODKFormsHandler also we have to use formsInteractor object to use the required methods in the ODKFeatureTesterActivity` 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
` This change would not affect in user perspective `

#### Does this change require updates to documentation?
` Yes, we need to update the readme.md file and move the required methods to appropriate places. `

2023-06-04 17:17 UTC, chinmoy12c requested changes
Thanks @shivenducs1136 the changes look fine :smile: . Just resolve the last nits.

2023-06-04 17:17 UTC, chinmoy12c commented on sample/src/main/java/io/samagra/oce_sample/ODKFeatureTesterActivity.kt
> +                formsInterctor = ODKProvider.getFormsInteractor()
nit, please correct the spelling of `formsInteractor`

2023-06-04 17:17 UTC, chinmoy12c commented on odk/extension/src/main/java/io/samagra/odk/collect/extension/handlers/ODKFormsHandler.kt
> +    private fun downloadAndOpenForm(formId: String, context: Context) {
Please add a newline here.

2023-06-04 17:17 UTC, chinmoy12c commented on odk/extension/src/main/java/io/samagra/odk/collect/extension/handlers/ODKFormsHandler.kt
> +    private fun mediaExists(form: Form): Boolean {
Please add a newline here.

2023-06-06 15:57 UTC, shivenducs1136 reviewed
Hey @chinmoy12c I have resolved those minor changes 😄, Hope it will work 👍🏻.

2023-06-07 13:08 UTC, merged