Prefill check
Samagra-Development/odk-collect-extension pull request #62
Opened 2023-06-07 15:45 UTC by prabs3257

Closes #27 

## Description

Please provide a brief description of the changes in this PR.

Added xml file and media check on prefill method

### Changes

List the changes done to fix a bug or introduce a new feature.

Added a new function in ODKFormHandler.kt

## Checklist

Please check the boxes below that apply:

- [X] All tests pass locally OR confirm CircleCI build passes.
- [X] Documentation has been updated or created, if applicable.

## How to Test
Please include any additional information or notes about testing here, if applicable.

## For UI-specific PRs only
If your PR includes UI-related changes, then:

Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes.   
Add a video showing the full UX flow.

2023-06-13 09:46 UTC, chinmoy12c requested changes

2023-06-13 09:46 UTC, chinmoy12c commented on odk/extension/src/main/java/io/samagra/odk/collect/extension/handlers/ODKFormsHandler.kt
> +    private fun checkForm(formId: String, tagValueMap: HashMap<String, String>){
Hey @prabs3257 I see there is some code repetition in this function [here](https://github.com/Samagra-Development/odk-collect-extension/blob/3a0017b9ecfd3d8beafc2812d2f7f7eb1e24a52d/odk/extension/src/main/java/io/samagra/odk/collect/extension/handlers/ODKFormsHandler.kt#L201). Can you extract out the form files checking code into a single function and call that function both from prefillForm() and openForm().

2023-06-13 10:37 UTC, prabs3257 commented
Heyy @chinmoy12c I have created a single check function now and used It in the prefillAndOpenForm() and openForm(). Please let me know if there are any additional changes needed 😃

2023-06-23 06:52 UTC, chinmoy12c commented on odk/extension/src/main/java/io/samagra/odk/collect/extension/handlers/ODKFormsHandler.kt
> +                formsNetworkInteractor.downloadFormById(formId, object : FileDownloadListener {
What happens if the download fails, how is that being handled?

2023-06-23 06:53 UTC, chinmoy12c requested changes

2023-06-23 06:53 UTC, chinmoy12c commented on odk/extension/src/main/java/io/samagra/odk/collect/extension/handlers/ODKFormsHandler.kt
> +
nit remove extra newlines.

2023-06-23 06:53 UTC, chinmoy12c commented on odk/extension/src/main/java/io/samagra/odk/collect/extension/handlers/ODKFormsHandler.kt
> +            }else{
nit `} else {`

2023-06-23 06:53 UTC, chinmoy12c commented on odk/extension/src/main/java/io/samagra/odk/collect/extension/handlers/ODKFormsHandler.kt
> +            }else {
nit `} else {`

2023-10-03 08:33 UTC, chinmoy12c commented
Closed in #64

2023-10-03 08:33 UTC, closed without merging